version: '2.1'
services:
  mediun_api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      COMMON_URL: '192.168.0.13'

      #MS_CRYPTO_VARIABLES
      CRYPTO_URL: '35.240.32.29'
      CRYPTO_PORT: '5001'
      CRYPTO_ENTRY: 'crypto'
      #MS_CONFIRMATION_VARIABLES
      CONFIRMATION_URL: '35.203.125.249'
      CONFIRMATION_PORT: '5002'
      CONFIRMATION_USERS_ENTRY: 'api/confirmation'
      #MS_AUTH_VARIABLES
      AUTH_URL: '35.226.188.252' #'192.168.0.17'
      AUTH_PORT: '5003'
      AUTH_ENTRY: 'auth'
      USERS_ENTRY: 'users'
      #MS_NOTIF_VARIABLES
      NOTIF_URL:  '35.234.173.101'
      NOTIF_PORT: '5004'
      NOTIF_ENTRY: 'users'
      #MS_APPOINTMENT_VARIABLES
      APPOINTMENT_URL: '34.74.190.194'
      APPOINTMENT_PORT: '5005'
      APPOINTMENT_ENTRY: 'schedules'
      #MS_EXCUSES_VARIABLES
      EXCUSES_URL: '34.83.81.244'
      EXCUSES_PORT: '5006'
      EXCUSES_ENTRY: 'medical_excuses'
      #MS_USERS_VARIABLES
      USERS_URL: '192.168.0.13'
      USERS_PORT: '5007'
      USERS_ENTRY: 'users'
    ports:
      - '5000:5000'
